# Generated by Django 3.2.2 on 2021-05-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='en_name',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ko_name',
            new_name='korean_name',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='en_name',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='ko_name',
            new_name='korean_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='en_name',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ko_name',
            new_name='korean_name',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='en_name',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='ko_name',
            new_name='korean_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='en_name',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='ko_name',
            new_name='korean_name',
        ),
    ]
