# Generated by Django 3.2.2 on 2021-05-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='backgorund_image',
            new_name='background_image',
        ),
    ]
